ayin-carmen/P2719 搞笑世界杯
=> ayin-carmen: 洛谷p2719

dislike/haitang/123.cpp
=> dislike: 我爱吃鸡腿

recolo111/test.cpp
某校大门外长度为 $l$ 的马路上有一排树，每两棵相邻的树之间的间隔都是 $1$ 米。我们可以把马路看成一个数轴，马路的一端在数轴 $0$ 的位置，另一端在 $l$ 的位置；数轴上的每个整数点，即 $0,1,2,\dots,l$，都种有一棵树。
由于马路上有一些区域要用来建地铁。这些区域用它们在数轴上的起始点和终止点表示。已知任一区域的起始点和终止点的坐标都是整数，区域之间可能有重合的部分。现在要把这些区域中的树（包括区域端点处的两棵树）移走。你的任务是计算将这些树都移走后，马路上还有多少棵树。
第一行有两个整数，分别表示马路的长度 $l$ 和区域的数目 $m$。
接下来 $m$ 行，每行两个整数 $u, v$，表示一个区域的起始点和终止点的坐标。
输出一行一个整数，表示将这些树都移走后，马路上剩余的树木数量。
```
500 3
150 300
100 200
470 471
```
```
298
```
**【数据范围】**
- 对于 $20\%$ 的数据，保证区域之间没有重合的部分。
- 对于 $100\%$ 的数据，保证 $1 \leq l \leq 10^4$，$1 \leq m \leq 100$，$0 \leq u \leq v \leq l$。
**【题目来源】**
NOIP 2005 普及组第二题
=> recolo111:luogu p1047

PlumYu/Readme.md
=> PlumYu: Create Readme.md

PlumYu/CodeForces/1899C.cpp
Solution in the case of arrays that do not require continuity。
=> PlumYu: 1899C

dislike/Codeforces Round 896 (Div. 2)A. Make It Zero.cpp
Codeforces Round 896 (Div. 2)
A. Make It Zero
=> dislike: CF

hahahaha/llluogu.cpp
一个 $n$ 个元素的整数数组，如果数组两个连续元素之间差的绝对值包括了 $[1,n-1]$ 之间的所有整数，则称之符合“欢乐的跳”，如数组 $\{1,4,2,3\}$ 符合“欢乐的跳”，因为差的绝对值分别为：$3,2,1$。
给定一个数组，你的任务是判断该数组是否符合“欢乐的跳”。
每组测试数据第一行以一个整数 $n(1 \le n \le 1000)$ 开始，接下来 $n$ 个空格隔开的在 $[-10^8,10^8]$ 之间的整数。
对于每组测试数据，输出一行若该数组符合“欢乐的跳”则输出 `Jolly`，否则输出 `Not jolly`。
```
4 1 4 2 3
```
```
Jolly
```
```
5 1 4 2 -1 6
```
```
Not jolly
```
$1 \le n \le 1000$
=> lisufan: 洛谷P1152

haitang/readme.md, haitang/轮转数组.cpp
给定一个整数数组 nums，将数组中的元素向右轮转 k 个位置，其中 k 是非负数。
=> haitang: leecode轮转数组

ayin-carmen/p：2028
龙兄在淘淘摘苹果的那个果园里摘了 $n$ 个完全互不相同的苹果，好客的园主为他提供了 $k$ 个篮子，他想把苹果装在篮子里拎回家（由于龙兄的手是无限大的，所以你不必考虑他能不能同时拎这么多篮子）。
同时，他不希望有任何一个篮子里是空的，因为这样就做不到物尽其用。因此他想知道一共有多少种放苹果的方法，由于他的大脑运算过慢，所以找到了聪明机智的你，他在摘苹果上已经花了很长时间，所以他只能等 $1$ 秒。
由于方法很可能非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常多，龙兄的大脑无法存储，所以他会给你一个数 $p$，输出方法数除以 $p$ 的余数就可以了。
一行三个数，依次为 $n$，$k$，$p$，含义如题面所示。
一个数，方法数除以 $p$ 的余数，行末有回车。
```
4 2 3
```
```
1
```
一共有 $4$ 个苹果，$2$ 个篮子。
有以下 $7$ 种方法。
- $\{1\},\{2,3,4\}$；
- $\{2\},\{1,3,4\}$；
- $\{3\},\{1,2,4\}$；
- $\{4\},\{1,2,3\}$；
- $\{1,2\},\{3,4\}$；
- $\{1,3\},\{2,4\}$；
- $\{1,4\},\{2,3\}$。
$7$ 除以 $3$ 余 $1$。
- 对于 $20\%$ 的数据，$n \le 8$，$k \le 8$。
- 对于 $60\%$ 的数据，$n \le 100$，$k \le 100$。
- 对于 $100\%$ 的数据，$n \le 10000$，$k \le 1000$。
保证所有数据 $n \ge k$，且答案在 $64$ 位整型范围内。
=> ayin-Carmen：洛谷p2028 龙兄摘苹果

chouxiaozilwh/B. SetsandUnion.cpp
Codeforces Round 899 (Div. 2)
B. Sets and Union
=> chouxiaozilwh: 11.20 打卡

ayin-carmen/P1794
德国放松对英国的进攻后，把矛头指向了东边——苏联。$1943$ 年初，东线的战斗进行到白热化阶段。据可靠情报，$90$ 余万德国军队在库尔斯克准备发动浩大攻势。因此，朱可夫元帅要求你立即从远东的军工厂运输大量装备支援库尔斯克前线。列车司机告诉你，一趟列车最多可以容纳 $V$ 体积的武器装备，但是你可能不能装满，因为列车承受不了那么大的重量，一趟列车最多可以承载 $C$ 单位的重量。同时，军工厂仓库提供给你一份装备清单，详细记录了每件装备的体积、重量和火力。为了有效支援朱可夫元帅，你要找到一种方案，使得总火力值最大。
第一行两个整数 $V$ 和 $G$，表示最大体积和重量。
第二行一个整数 $N$，表示仓库有 $N$ 件装备。
第三到 $N+2$ 行，每行 $3$ 个数 $T_i,V_i,G_i$，表示各装备的火力值、体积和重量。
输出一个数，表示可能获得的最大火力值。
```
6 5
4
10 2 2
20 3 2
40 4 3
30 3 3
```
```
50
```
对于 $100\%$ 的数据，$1\le V, G, N \le 500$。
=> ayin-carmen：洛谷p1794 装备运输

dislike/CFMilena and Admirer.cpp
=> Codeforces Round 910 (Div. 2)

wuyang/洛谷P1048.cpp
辰辰是个天资聪颖的孩子，他的梦想是成为世界上最伟大的医师。为此，他想拜附近最有威望的医师为师。医师为了判断他的资质，给他出了一个难题。医师把他带到一个到处都是草药的山洞里对他说：“孩子，这个山洞里有一些不同的草药，采每一株都需要一些时间，每一株也有它自身的价值。我会给你一段时间，在这段时间里，你可以采到一些草药。如果你是一个聪明的孩子，你应该可以让采到的草药的总价值最大。”
如果你是辰辰，你能完成这个任务吗？
第一行有 $2$ 个整数 $T$（$1 \le T \le 1000$）和 $M$（$1 \le  M \le 100$），用一个空格隔开，$T$ 代表总共能够用来采药的时间，$M$ 代表山洞里的草药的数目。
接下来的 $M$ 行每行包括两个在 $1$ 到 $100$ 之间（包括 $1$ 和 $100$）的整数，分别表示采摘某株草药的时间和这株草药的价值。
输出在规定的时间内可以采到的草药的最大总价值。
```
70 3
71 100
69 1
1 2
```
```
3
```
**【数据范围】**
- 对于 $30\%$ 的数据，$M \le 10$；
- 对于全部的数据，$M \le 100$。
**【题目来源】**
NOIP 2005 普及组第三题
=> wuyang: 洛谷P1048

dislike/Joyboard.cpp
Codeforces Round 902 (Div. 2): C
=> dislike: 23.11.21

chouxiaozilwh/D.DivideandEqualize.cpp
Codeforces Round 903 (Div. 3)
D. Divide and Equalize
=> chouxiaozilwh: 11.21 打卡

wuyang/洛谷P1616.cpp
此题为纪念 LiYuxiang 而生。
LiYuxiang 是个天资聪颖的孩子，他的梦想是成为世界上最伟大的医师。为此，他想拜附近最有威望的医师为师。医师为了判断他的资质，给他出了一个难题。医师把他带到一个到处都是草药的山洞里对他说：“孩子，这个山洞里有一些不同种类的草药，采每一种都需要一些时间，每一种也有它自身的价值。我会给你一段时间，在这段时间里，你可以采到一些草药。如果你是一个聪明的孩子，你应该可以让采到的草药的总价值最大。”
如果你是 LiYuxiang，你能完成这个任务吗？
此题和原题的不同点：
$1$. 每种草药可以无限制地疯狂采摘。
$2$. 药的种类眼花缭乱，采药时间好长好长啊！师傅等得菊花都谢了！
输入第一行有两个整数，分别代表总共能够用来采药的时间 $t$ 和代表山洞里的草药的数目 $m$。
第 $2$ 到第 $(m + 1)$ 行，每行两个整数，第 $(i + 1)$ 行的整数 $a_i, b_i$ 分别表示采摘第 $i$ 种草药的时间和该草药的价值。
输出一行，这一行只包含一个整数，表示在规定的时间内，可以采到的草药的最大总价值。
```
70 3
71 100
69 1
1 2
```
```
140
```
- 对于 $30\%$ 的数据，保证 $m \le 10^3$ 。
- 对于 $100\%$ 的数据，保证 $1 \leq m \le 10^4$，$1 \leq t \leq 10^7$，且 $1 \leq m \times t \leq 10^7$，$1 \leq a_i, b_i \leq 10^4$。
=> wuyang: 洛谷P1616疯狂采药

ayin-carmen/p1364
设有一棵二叉树，如图：
其中，圈中的数字表示结点中居民的人口。圈边上数字表示结点编号，现在要求在某个结点上建立一个医院，使所有居民所走的路程之和为最小，同时约定，相邻接点之间的距离为 $1$。如上图中，若医院建在 $1$ 处，则距离和 $=4+12+2\times20+2\times40=136$；若医院建在 $3$ 处，则距离和 $=4\times2+13+20+40=81$。
第一行一个整数 $n$，表示树的结点数。
接下来的 $n$ 行每行描述了一个结点的状况，包含三个整数 $w, u, v$，其中 $w$ 为居民人口数，$u$ 为左链接（为 $0$ 表示无链接），$v$ 为右链接（为 $0$ 表示无链接）。
一个整数，表示最小距离和。
```
5
13 2 3
4 0 0
12 4 5
20 0 0
40 0 0
```
```
81
```
对于 $100\%$ 的数据，保证 $1 \leq n \leq 100$，$0 \leq u, v \leq n$，$1 \leq w \leq 10^5$。
=> ayin-carmen：洛谷p1364

hahahaha/wodezuoye.cpp
有 $n$ 个人在一个水龙头前排队接水，假如每个人接水的时间为 $T_i$，请编程找出这 $n$ 个人排队的一种顺序，使得 $n$ 个人的平均等待时间最小。
第一行为一个整数 $n$。
第二行 $n$ 个整数，第 $i$ 个整数 $T_i$ 表示第 $i$ 个人的等待时间 $T_i$。
输出文件有两行，第一行为一种平均时间最短的排队顺序；第二行为这种排列方案下的平均等待时间（输出结果精确到小数点后两位）。
```
10
56 12 1 99 1000 234 33 55 99 812
```
```
3 2 7 8 1 4 9 6 10 5
291.90
```
$1\le n \leq 1000$，$1\le t_i \leq 10^6$，不保证 $t_i$ 不重复。
=> lisufan: 洛谷P1223

洪想想/2023/11/数的划分.cpp, 洪想想/2023/11/装备运输.cpp
将整数 $n$ 分成 $k$ 份，且每份不能为空，任意两个方案不相同（不考虑顺序）。
例如：$n=7$，$k=3$，下面三种分法被认为是相同的。
$1,1,5$;
$1,5,1$;
$5,1,1$.
问有多少种不同的分法。
$n,k$ （$6<n \le 200$，$2  \le k  \le  6$）
$1$ 个整数，即不同的分法。
```
7 3
```
```
4
```
四种分法为：
$1,1,5$;
$1,2,4$;
$1,3,3$;
$2,2,3$.
**【题目来源】**
NOIP 2001 提高组第二题
=> 洪想想：洛谷 1025

hahahaha/azaz.cpp
现有 $N(N\le 1000)$ 名同学参加了期末考试，并且获得了每名同学的信息：姓名（不超过 $8$ 个字符的字符串，没有空格）、语文、数学、英语成绩（均为不超过 $150$ 的自然数）。如果某对学生 $\text{<}i,j\text{>}$ 的每一科成绩的分差都不大于 $5$，且总分分差不大于 $10$，那么这对学生就是“旗鼓相当的对手”。现在我们想知道这些同学中，哪些是“旗鼓相当的对手”？请输出他们的姓名。
所有人的姓名是按照字典序给出的，输出时也应该按照字典序输出所有对手组合。也就是说，这对组合的第一个名字的字典序应该小于第二个；如果两个组合中第一个名字不一样，则第一个名字字典序小的先输出；如果两个组合的第一个名字一样但第二个名字不同，则第二个名字字典序小的先输出。
第一行输入一个正整数 $N$，表示学生个数。
第二行开始，往下 $N$ 行，对于每一行首先先输入一个字符串表示学生姓名，再输入三个自然数表示语文、数学、英语的成绩。均用空格相隔。
输出若干行，每行两个以空格隔开的字符串，表示一组旗鼓相当的对手。注意题目描述中的输出格式。
```
3
fafa 90 90 90
lxl 95 85 90
senpai 100 80 91
```
```
fafa lxl
lxl senpai
```
数据保证，$1 \leq N \leq 1000$，姓名为长度不超过 $8$ 的字符串，语文、数学、英语成绩均为不超过 $150$ 的自然数。
=> lisufan: 洛谷P5741

洪想想/2023/11/打开所有的灯.cpp
pmshz在玩一个益(ruo)智(zhi)的小游戏，目的是打开九盏灯所有的灯，这样的游戏难倒了pmshz。。。
这个灯很奇(fan)怪(ren)，点一下就会将这个灯和其周围四盏灯的开关状态全部改变。现在你的任务就是就是告诉pmshz要全部打开这些灯。
例如
```
0  1  1
1  0  0
1  0  1
```
点一下最中间的灯【2,2】就变成了
```
0  0  1
0  1  1
1  1  1
```
再点一下左上角的灯【1,1】就变成了
```
1  1  1
1  1  1
1  1  1
```
达成目标。最少需要2步。
输出2即可。
九个数字，3\*3的格式输入，每两个数字中间只有一个空格，表示灯初始的开关状态。（0表示关，1表示开）
1个整数，表示最少打开所有灯所需要的步数。
```
0 1 1
1 0 0
1 0 1
```
```
2
```
这个题水不水，就看你怎么考虑了。。。。
=> 洪想想：洛谷 2040

wuyang/洛谷P1049.cpp
有一个箱子容量为 $V$，同时有 $n$ 个物品，每个物品有一个体积。
现在从 $n$ 个物品中，任取若干个装入箱内（也可以不取），使箱子的剩余空间最小。输出这个最小值。
第一行共一个整数 $V$，表示箱子容量。
第二行共一个整数 $n$，表示物品总数。
接下来 $n$ 行，每行有一个正整数，表示第 $i$ 个物品的体积。
- 共一行一个整数，表示箱子最小剩余空间。
```
24
6
8
3
12
7
9
7
```
```
0
```
对于 $100\%$ 数据，满足 $0<n \le 30$，$1 \le V \le 20000$。
**【题目来源】**
NOIP 2001 普及组第四题
=> wuyang: 洛谷P1049

hahahaha/xixixi.cpp
有 $t$ 组数据。每组数据给出一个长度为 $n$ 的序列 $a$ 和一个数字 $k$。
请你判断 $a$ 中是否存在一个**非空子段**使得 $k$ 在这个子段中出现的次数**严格大于**其它数字的出现次数。存在输出 `YES`，否则输出 `NO`。
评测忽略大小写。例如，`yEs`、`Yes`、`yes`、`YES` 都表是肯定回答。
Translate by @[tianbiandeshenghuo11](/user/752485)
We define an integer to be the most common on a subsegment, if its number of occurrences on that subsegment is larger than the number of occurrences of any other integer in that subsegment. A subsegment of an array is a consecutive segment of elements in the array $ a $ .
Given an array $ a $ of size $ n $ , and an integer $ k $ , determine if there exists a non-empty subsegment of $ a $ where $ k $ is the most common element.
Each test consists of multiple test cases. The first line contains a single integer $ t $ ( $ 1 \le t \le 1000 $ ) — the number of test cases. The …
=> lisufan: cf

wuyang/洛谷P1255.cpp
楼梯有 $N$ 阶，上楼可以一步上一阶，也可以一步上二阶。
编一个程序，计算共有多少种不同的走法。
一个数字，楼梯数。
输出走的方式总数。
```
4
```
```
5
```
- 对于 $60\%$ 的数据，$N \leq 50$；
- 对于 $100\%$ 的数据，$1 \le N \leq 5000$。
=> wuyang: 洛谷P1255数楼梯

dislike/A.The Good Array.cpp
=> Codeforces Round 876 (Div. 2)

ayin-carmen/P2623 物品选取, ayin-carmen/p：1387
在一个 $n\times m$ 的只包含 $0$ 和 $1$ 的矩阵里找出一个不包含 $0$ 的最大正方形，输出边长。
输入文件第一行为两个整数 $n,m(1\leq n,m\leq 100)$，接下来 $n$ 行，每行 $m$ 个数字，用空格隔开，$0$ 或 $1$。
一个整数，最大正方形的边长。
```
4 4
0 1 1 1
1 1 1 0
0 1 1 0
1 1 0 1
```
```
2
```
=> ayin-carmen：洛谷p1387，最大正方形

洪想想/2023/11/猫粮计划.cpp
到中午了，机器猫要吃猫粮了。
机器猫掏出 $n$ 份食物，第 $i$ 份食物含有的能量为 $w[i]$。机器猫可以吃掉其中一些食物，获得这些食物的能量之和。
机器猫又不想变得太胖又不想变得太瘦，所以指定了一个目标区间 $[l, r]$。显然，可能有很多种选择食物的方式可以达成这个目标，因此机器猫想知道方案总数。
第一行，三个正整数 $n, l, r$。
第二行，$n$ 个正整数，表示每一份食物含有的能量 $w[i]$。
仅一行，一个整数，表示方案数。
```
4 70 85
10 10 20 50
```
```
4
```
所有方案如下：
选择食物 1, 2, 4，能量 10+10+50 = 70
选择食物 1, 3, 4，能量 10+20+50 = 80
选择食物 2, 3, 4，能量 10+20+50 = 80
选择食物 3, 4，能量 50+20 = 70
共 4 种方案。
对于 $50\%$ 的数据，满足 $n\leq 20$。
对于 $100\%$ 的数据，满足 $n\leq 40, 20\leq w[i] \leq 100, l\leq r \leq 300$。
提示：$w[i]$ 在范围内均匀随机生成。
=> 洪想想:洛谷 3624

wuyang/洛谷P1605.cpp
给定一个 $N \times M$ 方格的迷宫，迷宫里有 $T$ 处障碍，障碍处不可通过。
在迷宫中移动有上下左右四种方式，每次只能移动一个方格。数据保证起点上没有障碍。
给定起点坐标和终点坐标，每个方格最多经过一次，问有多少种从起点坐标到终点坐标的方案。
第一行为三个正整数 $N,M,T$，分别表示迷宫的长宽和障碍总数。
第二行为四个正整数 $SX,SY,FX,FY$，$SX,SY$ 代表起点坐标，$FX,FY$ 代表终点坐标。
接下来 $T$ 行，每行两个正整数，表示障碍点的坐标。
输出从起点坐标到终点坐标的方案总数。
```
2 2 1
1 1 2 2
1 2
```
```
1
```
对于 $100\%$ 的数据，$1 \le N,M \le 5$，$1 \le T \le 10$，$1 \le SX,FX \le n$，$1 \le SY,FY \le m$。
=> wuyang: 洛谷P1605迷宫

hahahaha/11.25.cpp
Sp 组织了一次举重比赛，有 $n$ 个运动员参加了比赛。其中每个运动员的力量为 $s_i$，耐力为 $e_i$。编号为 $1$ 的运动员是 [SA](https://www.luogu.com.cn/user/409236)，Sp 希望 SA 赢得比赛。
第 $i$ 名运动员**无法**举起重量 $w$ **严格大于**他的力量 $s_i$ 的杠铃，否则如果他能举起，他将举起 $e_i$ 次。举重比赛的获胜者为所有可以举起杠铃的人中举起次数最多的人。如果有多个，则没有获胜者。
Sp 希望 SA 成为获胜者，请确定一个杠铃重量 $w$ 使得 SA 成为获胜者。
Translated by [Shunpower](https://www.luogu.com.cn/user/399150).
Monocarp organizes a weightlifting competition. There are $ n $ athletes participating in the competition, the $ i $ -th athlete has strength $ s_i $ and endurance $ e_i $ . The $ 1 $ -st athlete is Monocarp's friend Polycarp, and Monocarp really wants Polycarp to win.
The competition will be conducted as follows. The jury will choose a positive (greater than zero) integer $ w $ , which denotes the weight of the barbell that will be used in the …
=> lisufan: 11.25CF div 2 A

洪想想/2023/11/产生数.cpp
给出一个整数 $n$ 和 $k$ 个变换规则。
规则：
- 一位数可变换成另一个一位数。
- 规则的右部不能为零。
例如：$n=234,k=2$。有以下两个规则：
- $2\longrightarrow 5$。
- $3\longrightarrow 6$。
上面的整数 $234$ 经过变换后可能产生出的整数为（包括原数）:
- $234$。
- $534$。
- $264$。
- $564$。
共 $4$ 种不同的产生数。
现在给出一个整数 $n$ 和 $k$ 个规则。求出经过任意次的变换（$0$ 次或多次），能产生出多少个不同整数。
仅要求输出个数。
第一行两个整数 $n,k$，含义如题面所示。
接下来 $k$ 行，每行两个整数 $x_i,y_i$，表示每条规则。
共一行，输出能生成的数字个数。
```
234 2
2 5
3 6
```
```
4
```
对于 $100\%$ 数据，满足 $n \lt 10^{30}$，$k \le 15$。
**【题目来源】**
NOIP 2002 普及组第三题
=> 洪想想:洛谷 1037

ayin-carmen/b8624 猫粮规划, ayin-carmen/石子合并
设有 $N(N \le 300)$ 堆石子排成一排，其编号为 $1,2,3,\cdots,N$。每堆石子有一定的质量 $m_i\ (m_i \le 1000)$。现在要将这 $N$ 堆石子合并成为一堆。每次只能合并相邻的两堆，合并的代价为这两堆石子的质量之和，合并后与这两堆石子相邻的石子将和新堆相邻。合并时由于选择的顺序不同，合并的总代价也不相同。试找出一种合理的方法，使总的代价最小，并输出最小代价。
第一行，一个整数 $N$。
第二行，$N$ 个整数 $m_i$。
输出文件仅一个整数，也就是最小代价。
```
4
2 5 3 1
```
```
22
```
=> ayin-carmen：洛谷P1775 石子合并（弱化版）

洪想想/2023/11/滑雪.cpp
Michael 喜欢滑雪。这并不奇怪，因为滑雪的确很刺激。可是为了获得速度，滑的区域必须向下倾斜，而且当你滑到坡底，你不得不再次走上坡或者等待升降机来载你。Michael 想知道在一个区域中最长的滑坡。区域由一个二维数组给出。数组的每个数字代表点的高度。下面是一个例子：
```plain
1   2   3   4   5
16  17  18  19  6
15  24  25  20  7
14  23  22  21  8
13  12  11  10  9
```
一个人可以从某个点滑向上下左右相邻四个点之一，当且仅当高度会减小。在上面的例子中，一条可行的滑坡为 $24-17-16-1$（从 $24$ 开始，在 $1$ 结束）。当然    $25$－$24$－$23$－$\ldots$－$3$－$2$－$1$ 更长。事实上，这是最长的一条。
输入的第一行为表示区域的二维数组的行数 $R$ 和列数 $C$。下面是 $R$ 行，每行有 $C$ 个数，代表高度(两个数字之间用 $1$ 个空格间隔)。
输出区域中最长滑坡的长度。
```
5 5
1 2 3 4 5
16 17 18 19 6
15 24 25 20 7
14 23 22 21 8
13 12 11 10 9
```
```
25
```
对于 $100\%$ 的数据，$1\leq R,C\leq 100$。
=> 洪想想：洛谷 1434

chouxiaozilwh/C.FlowerCityFence.cpp
CodeTON Round 7 (Div. 1 + Div. 2, Rated, Prizes!)
C. Matching Arrays
=> chouxiaozilwh: 11.26 补题

wuyang/洛谷P1036.cpp, wuyang/洛谷P1706.cpp
按照字典序输出自然数 $1$ 到 $n$ 所有不重复的排列，即 $n$ 的全排列，要求所产生的任一数字序列中不允许出现重复的数字。
一个整数 $n$。
由 $1 \sim n$ 组成的所有不重复的数字序列，每行一个序列。
每个数字保留 $5$ 个场宽。
```
3
```
```
1    2    3
1    3    2
2    1    3
2    3    1
3    1    2
3    2    1
```
$1 \leq n \leq 9$。
=> wuyang: P1706全排列问题

wuyang/洛谷P1060.cpp, wuyang/洛谷P1109.cpp
金明今天很开心，家里购置的新房就要领钥匙了，新房里有一间他自己专用的很宽敞的房间。更让他高兴的是，妈妈昨天对他说：“你的房间需要购买哪些物品，怎么布置，你说了算，只要不超过 $N$ 元钱就行”。今天一早金明就开始做预算，但是他想买的东西太多了，肯定会超过妈妈限定的 $N$ 元。于是，他把每件物品规定了一个重要度，分为 $5$ 等：用整数 $1-5$ 表示，第 $5$ 等最重要。他还从因特网上查到了每件物品的价格（都是整数元）。他希望在不超过 $N$ 元（可以等于 $N$ 元）的前提下，使每件物品的价格与重要度的乘积的总和最大。
设第$j$件物品的价格为 $v_j$，重要度为 $w_j$，共选中了 $k$ 件物品，编号依次为 $j_1,j_2,…,j_k$，则所求的总和为：
$v_{j_1} \times w_{j_1}+v_{j_2} \times w_{j_2} …+v_{j_k} \times w_{j_k}$。
请你帮助金明设计一个满足要求的购物单。
第一行，为 $2$ 个正整数，用一个空格隔开：$n,m$（$n<30000,m<25$）其中 $n$ 表示总钱数，$m$ 为希望购买物品的个数。
从第 $2$ 行到第 $m+1$ 行，第 $j$ 行给出了编号为 $j-1$ 的物品的基本数据，每行有 $2$ 个非负整数 $v,p$（其中 $v$ 表示该物品的价格 $(v \le 10000)$，$p$ 表示该物品的重要度（$1\le p\le5$）。
$1$ 个正整数，为不超过总钱数的物品的价格与重要度乘积的总和的最大值（$<100000000$）。
```
1000 5
800 2
400 5
300 5
400 3
200 2
```
```
3900
```
NOIP 2006 普及组 第二题
=> wuyang: 洛谷P1060开心的金明

hahahaha/11.27.cpp
国际乒联现在主席沙拉拉自从上任以来就立志于推行一系列改革，以推动乒乓球运动在全球的普及。其中 $11$ 分制改革引起了很大的争议，有一部分球员因为无法适应新规则只能选择退役。华华就是其中一位，他退役之后走上了乒乓球研究工作，意图弄明白 $11$ 分制和 $21$ 分制对选手的不同影响。在开展他的研究之前，他首先需要对他多年比赛的统计数据进行一些分析，所以需要你的帮忙。
华华通过以下方式进行分析，首先将比赛每个球的胜负列成一张表，然后分别计算在 $11$ 分制和 $21$ 分制下，双方的比赛结果（截至记录末尾）。
比如现在有这么一份记录，（其中 $\texttt W$ 表示华华获得一分，$\texttt L$ 表示华华对手获得一分）：
$\texttt{WWWWWWWWWWWWWWWWWWWWWWLW}$
在 $11$ 分制下，此时比赛的结果是华华第一局 $11$ 比 $0$ 获胜，第二局 $11$ 比 $0$ 获胜，正在进行第三局，当前比分 $1$ 比 $1$。而在 $21$ 分制下，此时比赛结果是华华第一局 $21$ 比 $0$ 获胜，正在进行第二局，比分 $2$ 比 $1$。如果一局比赛刚开始，则此时比分为 $0$ 比 $0$。直到分差大于或者等于 $2$，才一局结束。
你的程序就是要对于一系列比赛信息的输入（$\texttt{WL}$ 形式），输出正确的结果。
每个输入文件包含若干行字符串，字符串有大写的 $\texttt W$ 、 $\texttt L$ 和 $\texttt E$ 组成。其中 $\texttt E$ 表示比赛信息结束，程序应该忽略 $\texttt E$ 之后的所有内容。
输出由两部分组成，每部分有若干行，每一行对应一局比赛的比分（按比赛信息输入顺序）。其中第一部分是 $11$ 分制下的结果，第二部分是 $21$ …
=> lisufan: luoguP1042

ayin-carmen/P1776 宝物筛选.cpp
终于，破解了千年的难题。小 FF 找到了王室的宝物室，里面堆满了无数价值连城的宝物。
这下小 FF 可发财了，嘎嘎。但是这里的宝物实在是太多了，小 FF 的采集车似乎装不下那么多宝物。看来小 FF 只能含泪舍弃其中的一部分宝物了。
小 FF 对洞穴里的宝物进行了整理，他发现每样宝物都有一件或者多件。他粗略估算了下每样宝物的价值，之后开始了宝物筛选工作：小 FF 有一个最大载重为 $W$ 的采集车，洞穴里总共有 $n$ 种宝物，每种宝物的价值为 $v_i$，重量为 $w_i$，每种宝物有 $m_i$ 件。小 FF 希望在采集车不超载的前提下，选择一些宝物装进采集车，使得它们的价值和最大。
第一行为一个整数 $n$ 和 $W$，分别表示宝物种数和采集车的最大载重。
接下来 $n$ 行每行三个整数 $v_i,w_i,m_i$。
输出仅一个整数，表示在采集车不超载的情况下收集的宝物的最大价值。
```
4 20
3 9 3
5 9 1
9 4 2
8 1 3
```
```
47
```
对于 $30\%$ 的数据，$n\leq \sum m_i\leq 10^4$，$0\le W\leq 10^3$。
对于 $100\%$ 的数据，$n\leq \sum m_i \leq 10^5$，$0\le W\leq 4\times 10^4$，$1\leq n\le 100$。
=> ayin-caremn：p1776 宝物筛选

wuyang/洛谷P1044.cpp, wuyang/洛谷P1115.cpp
栈是计算机中经典的数据结构，简单的说，栈就是限制在一端进行插入删除操作的线性表。
栈有两种最重要的操作，即 pop（从栈顶弹出一个元素）和 push（将一个元素进栈）。
栈的重要性不言自明，任何一门数据结构的课程都会介绍栈。宁宁同学在复习栈的基本概念时，想到了一个书上没有讲过的问题，而他自己无法给出答案，所以需要你的帮忙。
宁宁考虑的是这样一个问题：一个操作数序列，$1,2,\ldots ,n$（图示为 1 到 3 的情况），栈 A 的深度大于 $n$。
现在可以进行两种操作，
1. 将一个数，从操作数序列的头端移到栈的头端（对应数据结构栈的 push 操作）
2. 将一个数，从栈的头端移到输出序列的尾端（对应数据结构栈的 pop 操作）
使用这两种操作，由一个操作数序列就可以得到一系列的输出序列，下图所示为由 `1 2 3` 生成序列 `2 3 1` 的过程。
（原始状态如上图所示）
你的程序将对给定的 $n$，计算并输出由操作数序列 $1,2,\ldots,n$ 经过操作可能得到的输出序列的总数。
输入文件只含一个整数 $n$（$1 \leq n \leq 18$）。
输出文件只有一行，即可能输出序列的总数目。
```
3
```
```
5
```
**【题目来源】**
NOIP 2003 普及组第三题
=> wuyang: 洛谷P1044栈

ayin-carmen/P4391 [BOI2009] Radio Transmission 无线传输.cpp
给你一个字符串 $s_1$，它是由某个字符串 $s_2$ 不断自我连接形成的（保证至少重复 $2$ 次）。但是字符串 $s_2$ 是不确定的，现在只想知道它的最短长度是多少。
第一行一个整数 $L$，表示给出字符串的长度。
第二行给出字符串 $s_1$ 的一个子串，全由小写字母组成。
仅一行，表示 $s_2$ 的最短长度。
```
8
cabcabca
```
```
3
```
对于样例，我们可以利用 $\texttt{abc}$ 不断自我连接得到 $\texttt{abcabcabcabc}$，读入的 $\texttt{cabcabca}$，是它的子串。
对于全部的测试点，保证 $1 < L \le 10^6$。
=> ayin-carmen：p4391 无线传输

wuyang/洛谷P1077.cpp
小明的花店新开张，为了吸引顾客，他想在花店的门口摆上一排花，共 $m$ 盆。通过调查顾客的喜好，小明列出了顾客最喜欢的 $n$ 种花，从 $1$ 到 $n$ 标号。为了在门口展出更多种花，规定第 $i$ 种花不能超过 $a_i$ 盆，摆花时同一种花放在一起，且不同种类的花需按标号的从小到大的顺序依次摆列。
试编程计算，一共有多少种不同的摆花方案。
第一行包含两个正整数 $n$ 和 $m$，中间用一个空格隔开。
第二行有 $n$ 个整数，每两个整数之间用一个空格隔开，依次表示 $a_1,a_2, \cdots ,a_n$。
一个整数，表示有多少种方案。注意：因为方案数可能很多，请输出方案数对 $10^6+7$ 取模的结果。
```
2 4
3 2
```
```
2
```
【数据范围】
对于 $20\%$ 数据，有 $0<n \le 8,0<m \le 8,0 \le a_i \le 8$。
对于 $50\%$ 数据，有 $0<n \le 20,0<m \le 20,0 \le a_i \le 20$。
对于 $100\%$ 数据，有 $0<n \le 100,0<m \le 100,0 \le a_i \le 100$。
NOIP 2012 普及组 第三题
=> wuyang: 洛谷P1077摆花

洪想想/2023/11/无线传输.cpp
https://www.luogu.com.cn/problem/P4391
=> 洛谷： 洪想想 4391

hahahaha/11.30.cpp
明明想在学校中请一些同学一起做一项问卷调查，为了实验的客观性，他先用计算机生成了 $N$ 个 $1$ 到 $1000$ 之间的随机整数 $(N\leq100)$，对于其中重复的数字，只保留一个，把其余相同的数去掉，不同的数对应着不同的学生的学号。然后再把这些数从小到大排序，按照排好的顺序去找同学做调查。请你协助明明完成“去重”与“排序”的工作。
输入有两行，第 $1$ 行为 $1$ 个正整数，表示所生成的随机数的个数 $N$。
第 $2$ 行有 $N$ 个用空格隔开的正整数，为所产生的随机数。
输出也是两行，第 $1$ 行为 $1$ 个正整数 $M$，表示不相同的随机数的个数。
第 $2$ 行为 $M$ 个用空格隔开的正整数，为从小到大排好序的不相同的随机数。
```
10
20 40 32 67 40 20 89 300 400 15
```
```
8
15 20 32 40 67 89 300 400
```
NOIP 2006 普及组 第一题
=> lisufan: 洛谷P059

hahahaha/11.2.cpp, hahahaha/12.1.cpp, hahahaha/azazaz.cpp
https://codeforces.com/problemset/problem/1901/A
=> lisufan: CF round158 div.2 A

hahahaha/nnnnn
https://codeforces.com/contest/1881/problem/B
=> lsf: CFRound 903 (Div. 3)

lsf: cf round913 div3 A
https://codeforces.com/contest/1907/problem/A
=> Create lsf: cf round913 div3 A

round 913 div3 A
https://codeforces.com/contest/1907/problem/A
=> Create round 913 div3 A

hahahaha/12.6.cpp
https://codeforces.com/contest/1907/problem/A
=> lisufan: CFround913 Div3 A

hahahaha/2024.1.5.cpp
https://codeforces.com/contest/1850/problem/B
=> Codeforces Round 886 (Div. 4)

洪想想/医院设置.cpp, 洪想想/口袋的天空.cpp
https://www.luogu.com.cn/problem/P1364
3a9ed6137e48e3742889f105a3167f6d1fb42b16
=> 洪想想：洛谷：1364

hahahaha/1.11.cpp
https://leetcode.cn/problems/ransom-note/description/
=> 力扣：383. 赎金信

hahahaha/1.16.cpp
https://codeforces.com/contest/1914/problem/A
=> Codeforces Round 916 (Div. 3) A

ayin-carmen/P1821 [USACO07FEB] Cow Party S.cpp
https://www.luogu.com.cn/problem/P1821
=> ayin-carmen：洛谷p1821

hahahaha/luogo.cpp
https://www.luogu.com.cn/problem/P2249
=> 洛谷P2249 【深基13.例1】查找
